language: python

python:
  - 3.6.5

services: postgresql

env:
  - DJANGO=2.1.0

before_install:
  - export DJANGO_SETTINGS_MODULE=website.settings
  - export PYTHONPATH=$HOME/build/younganakin/python-interview
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE msoko;" -U postgres
  - cd website
  - python manage.py migrate

script:
  - python manage.py test
